# Generated by Django 5.2.6 on 2025-09-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.administradores')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante')),
            ],
            options={
                'verbose_name': 'Estudiante Autorizado',
                'verbose_name_plural': 'Estudiantes Autorizados',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicaciones.estudianteautorizado')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
